version: '2'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.node
            args:
                PACKAGE_PATH: ./api/package.json
                WORKING_DIR: /src/api
        env_file:
            - ./common.env
        volumes:
            - .:/src
        command: ["npm", "run", "start-dev"]
    redis:
        image: redis
