version: '2'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.node
            args:
                PACKAGE_PATH: ./api/package.json
                WORKING_DIR: /src/api
        env_file:
            - ./common.env
        volumes:
            - .:/src
        depends_on:
            - postgres
            - redis
            - migrate-seed
        entrypoint: ./wait-for-it.sh -t 0 postgres:5432 --
        command: ["npm", "run", "start-dev"]
    postgres:
        image: postgres:9.6.1
        env_file:
            - ./common.env
    redis:
        image: redis
    migrate-seed:
        build:
            context: .
            dockerfile: Dockerfile.node
            args:
                PACKAGE_PATH: ./api/package.json
                WORKING_DIR: /src/api
        env_file:
            - ./common.env
        volumes:
            - .:/src
        depends_on:
            - postgres
        entrypoint: ./wait-for-it.sh -t 0 postgres:5432 --
        command: ["npm", "run", "migrate-seed"]
